"""Synchronize canonical SKILL.md folders into agent-specific skill surfaces.

Default behavior is a dry run. Pass --apply to write files.
"""

from __future__ import annotations

import argparse
import json
import shutil
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


GENERATED_MARKER = "Generated by sync_skills_universal.py"
MANIFEST_NAME = ".skill-sync-manifest.json"
DEFAULT_TARGETS = ("codex", "claude", "agents", "cursor", "antigravity")


@dataclass(frozen=True)
class Skill:
    name: str
    path: Path


@dataclass(frozen=True)
class TargetSpec:
    name: str
    relative_path: Path
    mode: str
    description: str


def available_target_specs() -> dict[str, TargetSpec]:
    return {
        "codex": TargetSpec(
            name="codex",
            relative_path=Path(".codex") / "skills",
            mode="directory",
            description="Project-local Codex skills: .codex/skills/<skill>/SKILL.md",
        ),
        "claude": TargetSpec(
            name="claude",
            relative_path=Path(".claude") / "skills",
            mode="directory",
            description="Project-local Claude Code skills: .claude/skills/<skill>/SKILL.md",
        ),
        "agents": TargetSpec(
            name="agents",
            relative_path=Path(".agents") / "skills",
            mode="directory",
            description="Generic local agent skills: .agents/skills/<skill>/SKILL.md",
        ),
        "antigravity": TargetSpec(
            name="antigravity",
            relative_path=Path(".gemini") / "antigravity" / "skills",
            mode="directory",
            description="Gemini Antigravity skills: .gemini/antigravity/skills/<skill>/SKILL.md",
        ),
        "cursor": TargetSpec(
            name="cursor",
            relative_path=Path(".cursor") / "rules",
            mode="cursor-mdc",
            description="Cursor rules generated from SKILL.md: .cursor/rules/<skill>.mdc",
        ),
    }


def discover_skills(source_dir: Path | str, skill_names: Iterable[str] | None = None) -> list[Skill]:
    source = Path(source_dir)
    requested = set(skill_names or [])
    if not source.exists():
        raise FileNotFoundError(f"Source skills directory does not exist: {source}")
    if not source.is_dir():
        raise NotADirectoryError(f"Source skills path is not a directory: {source}")

    skills: list[Skill] = []
    for child in sorted(source.iterdir(), key=lambda p: p.name.lower()):
        if not child.is_dir() or child.name.startswith("."):
            continue
        if requested and child.name not in requested:
            continue
        skill_file = child / "SKILL.md"
        if skill_file.exists():
            skills.append(Skill(name=child.name, path=child))

    missing = sorted(requested - {skill.name for skill in skills})
    if missing:
        raise ValueError(f"Requested skills not found: {', '.join(missing)}")
    return skills


def sync_targets(
    source_dir: Path | str,
    project_root: Path | str,
    target_names: Iterable[str] | None = None,
    apply: bool = False,
    clean: bool = False,
    skill_names: Iterable[str] | None = None,
) -> dict:
    specs = available_target_specs()
    selected = list(target_names or DEFAULT_TARGETS)
    unknown = sorted(set(selected) - set(specs))
    if unknown:
        raise ValueError(f"Unknown targets: {', '.join(unknown)}")

    root = Path(project_root).resolve()
    skills = discover_skills(source_dir, skill_names=skill_names)
    plan = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "dry_run": not apply,
        "source_dir": str(Path(source_dir).resolve()),
        "project_root": str(root),
        "summary": {
            "skills": len(skills),
            "targets": len(selected),
            "planned": 0,
            "would_write": 0,
            "written": 0,
            "removed": 0,
        },
        "targets": [],
    }

    for target_name in selected:
        spec = specs[target_name]
        target_root = (root / spec.relative_path).resolve()
        _ensure_target_is_safe(root, target_root)

        target_plan = {
            "name": target_name,
            "mode": spec.mode,
            "path": str(target_root),
            "actions": [],
        }

        if spec.mode == "directory":
            _plan_directory_target(target_root, target_plan, skills, apply)
        elif spec.mode == "cursor-mdc":
            _plan_cursor_target(target_root, target_plan, skills, apply)
        else:
            raise ValueError(f"Unsupported target mode: {spec.mode}")

        if clean:
            _clean_stale_managed_entries(target_root, target_plan, skills, spec, apply)

        if apply:
            _write_manifest(target_root, spec, skills)

        plan["summary"]["planned"] += len(target_plan["actions"])
        write_actions = sum(1 for item in target_plan["actions"] if item["action"] == "write")
        remove_actions = sum(1 for item in target_plan["actions"] if item["action"] == "remove")
        plan["summary"]["would_write"] += write_actions
        plan["summary"]["written"] += write_actions if apply else 0
        plan["summary"]["removed"] += remove_actions if apply else 0
        plan["targets"].append(target_plan)

    return plan


def _plan_directory_target(target_root: Path, target_plan: dict, skills: list[Skill], apply: bool) -> None:
    for skill in skills:
        destination = target_root / skill.name
        target_plan["actions"].append(
            {
                "action": "write",
                "kind": "skill-directory",
                "skill": skill.name,
                "destination": str(destination),
            }
        )
        if apply:
            target_root.mkdir(parents=True, exist_ok=True)
            _replace_directory(skill.path, destination)


def _plan_cursor_target(target_root: Path, target_plan: dict, skills: list[Skill], apply: bool) -> None:
    for skill in skills:
        source_text = (skill.path / "SKILL.md").read_text(encoding="utf-8")
        destination = target_root / f"{skill.name}.mdc"
        target_plan["actions"].append(
            {
                "action": "write",
                "kind": "cursor-rule",
                "skill": skill.name,
                "destination": str(destination),
            }
        )
        if apply:
            target_root.mkdir(parents=True, exist_ok=True)
            destination.write_text(_cursor_rule_content(skill.name, source_text), encoding="utf-8")


def _cursor_rule_content(skill_name: str, source_text: str) -> str:
    return (
        "---\n"
        "alwaysApply: false\n"
        f"description: Synced skill rule for {skill_name}\n"
        "---\n\n"
        f"<!-- {GENERATED_MARKER}; source=skills/{skill_name}/SKILL.md -->\n\n"
        f"{source_text.rstrip()}\n"
    )


def _clean_stale_managed_entries(
    target_root: Path,
    target_plan: dict,
    skills: list[Skill],
    spec: TargetSpec,
    apply: bool,
) -> None:
    manifest = _read_manifest(target_root)
    current = {skill.name for skill in skills}
    stale = sorted(set(manifest.get("managed_skills", [])) - current)
    for skill_name in stale:
        destination = target_root / (f"{skill_name}.mdc" if spec.mode == "cursor-mdc" else skill_name)
        target_plan["actions"].append(
            {
                "action": "remove",
                "kind": "stale-managed-entry",
                "skill": skill_name,
                "destination": str(destination),
            }
        )
        if apply and destination.exists():
            _remove_path(destination, target_root)


def _read_manifest(target_root: Path) -> dict:
    path = target_root / MANIFEST_NAME
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def _write_manifest(target_root: Path, spec: TargetSpec, skills: list[Skill]) -> None:
    target_root.mkdir(parents=True, exist_ok=True)
    manifest = {
        "generated_by": "sync_skills_universal.py",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "target": spec.name,
        "mode": spec.mode,
        "managed_skills": [skill.name for skill in skills],
    }
    (target_root / MANIFEST_NAME).write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _replace_directory(source: Path, destination: Path) -> None:
    if destination.exists():
        _remove_path(destination, destination.parent)
    shutil.copytree(
        source,
        destination,
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )


def _remove_path(path: Path, allowed_root: Path) -> None:
    resolved = path.resolve()
    root = allowed_root.resolve()
    if not resolved.is_relative_to(root):
        raise ValueError(f"Refusing to remove path outside target root: {resolved}")
    if path.is_symlink() or path.is_file():
        path.unlink()
    elif path.is_dir():
        shutil.rmtree(path)


def _ensure_target_is_safe(project_root: Path, target_root: Path) -> None:
    if target_root == project_root:
        raise ValueError("Refusing to sync directly into the project root")
    if not target_root.is_relative_to(project_root):
        raise ValueError(f"Target must be inside project root: {target_root}")


def format_plan(plan: dict) -> str:
    lines = [
        "Skill sync plan",
        f"Mode: {'dry-run' if plan['dry_run'] else 'apply'}",
        f"Source: {plan['source_dir']}",
        f"Skills: {plan['summary']['skills']}",
        f"Targets: {plan['summary']['targets']}",
        f"Planned actions: {plan['summary']['planned']}",
        f"Would write: {plan['summary']['would_write']}",
        f"Written: {plan['summary']['written']}",
        f"Removed: {plan['summary']['removed']}",
    ]
    for target in plan["targets"]:
        lines.append(f"- {target['name']} -> {target['path']} ({len(target['actions'])} actions)")
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    specs = available_target_specs()
    parser = argparse.ArgumentParser(description="Synchronize canonical skills into agent surfaces.")
    parser.add_argument("--source", default="skills", help="Canonical skills directory. Default: skills")
    parser.add_argument("--project", default=".", help="Project root that receives agent folders. Default: .")
    parser.add_argument(
        "--target",
        action="append",
        dest="targets",
        choices=sorted(specs),
        help="Target to sync. May be repeated. Default: common targets.",
    )
    parser.add_argument("--all", action="store_true", help="Sync all known targets.")
    parser.add_argument("--skill", action="append", dest="skills", help="Limit sync to a skill. May be repeated.")
    parser.add_argument("--apply", action="store_true", help="Write files. Without this flag, only prints a dry run.")
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove stale entries only when they were listed in the previous target manifest.",
    )
    parser.add_argument("--json", action="store_true", help="Print the plan as JSON.")
    parser.add_argument("--list-targets", action="store_true", help="List available targets and exit.")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    specs = available_target_specs()
    if args.list_targets:
        for name in sorted(specs):
            print(f"{name}: {specs[name].description}")
        return 0

    targets = sorted(specs) if args.all else args.targets
    plan = sync_targets(
        source_dir=Path(args.source),
        project_root=Path(args.project),
        target_names=targets,
        apply=args.apply,
        clean=args.clean,
        skill_names=args.skills,
    )
    if args.json:
        print(json.dumps(plan, indent=2, sort_keys=True))
    else:
        print(format_plan(plan))
        if plan["dry_run"]:
            print("Dry run only. Re-run with --apply to write files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
