#!/bin/bash
# Bulk upgrade: add pre-run checklist + feedback step + learnings.md
# Runs additively; skips parts already present.

set -e
SKILLS_DIR="/root/.claude/skills"
LOG="/tmp/skill-upgrade.log"
> "$LOG"

cd "$SKILLS_DIR"

for d in */; do
  name="${d%/}"
  skill_file="$d/SKILL.md"
  [ "$name" = "gstack" ] && continue
  [ ! -f "$skill_file" ] && continue

  # === Step A: create learnings.md if missing ===
  if [ ! -f "$d/learnings.md" ]; then
    human=$(echo "$name" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++)$i=toupper(substr($i,1,1))substr($i,2)}1')
    cat > "$d/learnings.md" <<LEARNINGS
# Learnings — $human
_Auto-generated by skill upgrade. Fill in through use._

## Non-Negotiable Rules
<!-- Rules here are ALWAYS applied on every single run. Never skip them. -->
<!-- Format: - [YYYY-MM-DD] Rule description -->

## Patterns Observed
<!-- Running log of user corrections and preferences -->
<!-- Format: - [YYYY-MM-DD] What happened / what the user preferred -->

## Applied Corrections
<!-- When a pattern appears 2+ times, promote it to Non-Negotiable Rules -->
LEARNINGS
    echo "[learnings] created: $name" >> "$LOG"
  fi

  # === Step B: add Pre-Run Checklist after frontmatter ===
  if ! grep -qi "pre-run checklist" "$skill_file"; then
    python3 - "$skill_file" <<'PYEOF'
import sys, re
p = sys.argv[1]
with open(p) as f:
    content = f.read()

block = """
## Pre-Run Checklist (always execute before Step 1)
1. Check if ./learnings.md exists → if yes, READ it now and apply ALL "Non-Negotiable Rules" for this entire session.
2. Check if ../brand-context/voice-profile.md exists → if this skill produces any written output (posts, emails, reports, copy) → load it.
3. Check if ../brand-context/icp.md exists → if this skill involves audience targeting, research, or content → load it.

"""

# Find end of frontmatter (second occurrence of --- at line start)
if content.startswith("---"):
    m = re.search(r'^---\s*$', content[4:], re.MULTILINE)
    if m:
        end_of_fm = 4 + m.end()
        # skip trailing whitespace/newline after closing ---
        rest = content[end_of_fm:]
        rest_lstripped = rest.lstrip('\n')
        new = content[:end_of_fm] + "\n" + block + rest_lstripped
    else:
        new = block + content
else:
    new = block + content

with open(p, 'w') as f:
    f.write(new)
PYEOF
    echo "[pre-run] added: $name" >> "$LOG"
  fi

  # === Step C: append Feedback Loop step at end ===
  if ! grep -qi "feedback loop\|self-improvement\|rate this output" "$skill_file"; then
    cat >> "$skill_file" <<'FEEDBACK'

## Feedback Loop & Self-Improvement

After delivering the final output:
1. Ask the user exactly this: "Rate this output 1–5. What should I do differently next time? (press Enter to skip)"
2. If the user provides feedback:
   a. Open ./learnings.md
   b. Under "Patterns Observed" → append: `- [today's date] [feedback summary]`
   c. Check "Patterns Observed" — if the same type of correction appears 2 or more times → add it as a new rule under "Non-Negotiable Rules"
   d. Save learnings.md
3. On next run: Pre-Run Checklist (top of this file) ensures rules are loaded first.
FEEDBACK
    echo "[feedback] added: $name" >> "$LOG"
  fi
done

echo "DONE" >> "$LOG"
wc -l "$LOG"
