import json
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import sync_skills_universal as sync


def write_skill(root, name, body="Body"):
    skill_dir = root / name
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text(
        "---\n"
        f"name: {name}\n"
        f"description: Use when testing {name}.\n"
        "---\n"
        "\n"
        f"# {name}\n"
        f"{body}\n",
        encoding="utf-8",
    )
    evals_dir = skill_dir / "evals"
    evals_dir.mkdir()
    (evals_dir / "sample.json").write_text('{"id":"sample"}\n', encoding="utf-8")
    return skill_dir


class SyncSkillsUniversalTests(unittest.TestCase):
    def test_discover_skills_reads_only_skill_directories(self):
        with tempfile.TemporaryDirectory() as tmp:
            skills_dir = Path(tmp) / "skills"
            write_skill(skills_dir, "beta")
            write_skill(skills_dir, "alpha")
            (skills_dir / "notes").mkdir()
            (skills_dir / ".hidden").mkdir()

            skills = sync.discover_skills(skills_dir)

            self.assertEqual([skill.name for skill in skills], ["alpha", "beta"])

    def test_dry_run_does_not_write_target_files(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            skills_dir = root / "skills"
            write_skill(skills_dir, "paid-ai-niche-discovery")

            plan = sync.sync_targets(
                source_dir=skills_dir,
                project_root=root,
                target_names=["codex"],
                apply=False,
            )

            self.assertEqual(plan["summary"]["skills"], 1)
            self.assertEqual(plan["summary"]["targets"], 1)
            self.assertFalse((root / ".codex" / "skills").exists())

    def test_apply_copies_skill_directories_and_manifest(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            skills_dir = root / "skills"
            write_skill(skills_dir, "paid-ai-niche-discovery")

            plan = sync.sync_targets(
                source_dir=skills_dir,
                project_root=root,
                target_names=["codex", "claude"],
                apply=True,
            )

            for target in (".codex", ".claude"):
                target_skill = root / target / "skills" / "paid-ai-niche-discovery"
                self.assertTrue((target_skill / "SKILL.md").exists())
                self.assertTrue((target_skill / "evals" / "sample.json").exists())
                manifest = json.loads(
                    (root / target / "skills" / ".skill-sync-manifest.json").read_text(
                        encoding="utf-8"
                    )
                )
                self.assertEqual(manifest["managed_skills"], ["paid-ai-niche-discovery"])

            self.assertEqual(plan["summary"]["written"], 2)

    def test_cursor_export_writes_mdc_rules_with_generated_header(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            skills_dir = root / "skills"
            write_skill(skills_dir, "youtube-growth-system", body="Use this for YouTube.")

            sync.sync_targets(
                source_dir=skills_dir,
                project_root=root,
                target_names=["cursor"],
                apply=True,
            )

            rule_path = root / ".cursor" / "rules" / "youtube-growth-system.mdc"
            rule_text = rule_path.read_text(encoding="utf-8")
            self.assertIn("Generated by sync_skills_universal.py", rule_text)
            self.assertIn("# youtube-growth-system", rule_text)


if __name__ == "__main__":
    unittest.main()
